### PR TITLE
Fix owe command overflow

### LINKED ISSUE #224: Owe command does not catch overflow
Owe does not catch overflow when input is more than max_value, or when calculated value is more than max_value.

### PR DESCRIPTION
**Pull request by DennieDan**
Closes #224 #230 #237 
The `OweCommand` is unable to catch the overflow of the new `OwedAmount` value, which results in an inappropriate user-side message

Let's:
- Catch the overflow during `OwedAmount` calculation
- Update the "double to string" conversion method to prevent bug-prone cases

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -24,7 +27,11 @@ public class Messages {
                 "Multiple values specified for the following single-valued field(s): ";
     public static final String MESSAGE_HAS_CLASHES = "\nYou have %d other students with clashing schedule:\n%s";
     public static final String MESSAGE_REMINDER = "Reminder(s) for %s:\n";
-
+    public static final String MESSAGE_LIMIT = "Your request exceeds the "
+            + "maximum allowable for this application."
+            + "\nMaximum Rate: $" + String.format("%.2f", Rate.MAX_VALUE)
+            + "\nMaximum Paid Amount: $" + String.format("%.2f", PaidAmount.MAX_VALUE)
+            + "\nMaximum Owed Amount: $" + String.format("%.2f", OwedAmount.MAX_VALUE);
```
Comment (TY1Fan) [inline src/main/java/seedu/address/logic/Messages.java:34]: Nice! I think your MESSAGE_LIMIT seems better.

**Review by TY1Fan — APPROVED** [review]
LGTM
